{% set version = "dev_v1.26.0" %}

package:
  name: featuretools
  version: {{ version }}

source:
  url: https://test-files.pythonhosted.org/packages/2f/ab/9e8d52eeb2cfe46c39cedd863064ce73236013a26c04c0021339b2025ba3/featuretools-0.26.0.dev1.tar.gz
  sha256: d5ebfd077fc1119cf8f534af53260bff96db312fd727ca91f87ba2b70c5acbc9

build:
  entry_points:
    - featuretools = featuretools.__main__:cli
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7.*
  run:
    - click >=7.0.0
    - cloudpickle >=0.4.0
    - dask >=2.12.0
    - distributed >=2.12.0
    - numpy >=1.16.6
    - pandas >=1.2.0,<2.0.0
    - psutil >=5.6.6
    - python >=3.7.*
    - pyyaml >=5.4
    - scipy >=1.3.2
    - tqdm >=4.32.0

test:
  commands:
    - featuretools --help
    - featuretools info
    - featuretools list-primitives
    - pytest --pyargs featuretools
  imports:
    - featuretools
  requires:
    - boto3 >=1.17.46
    - composeml >=0.3.0
    - fastparquet==0.5.0
    - graphviz !=2.47.2
    - moto >=1.3.15
    - pip >=21.1.2
    - pympler >=0.8
    - pytest >=5.2.*
    - python-graphviz >=0.8.4
    - smart_open >=5.0.*
    - urllib3 >=1.26.5
    - pyarrow >=3.0.0
  source_files:
    - featuretools/*

about:
  doc_url: https://featuretools.alteryx.com
  dev_url: https://github.com/alteryx/Featuretools
  home: https://www.featuretools.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a framework for automated feature engineering

extra:
  recipe-maintainers:
    - gsheni
    - rwedge
