{% set version = "0.19.0.dev0" %}

package:
  name: featuretools
  version: {{ version }}

source:
  url: https://test-files.pythonhosted.org/packages/91/40/fa0584a1139f92cbbcf6781e8a94a6a163d6a246e4c617ce5db4de886c8f/featuretools-0.19.0.dev0.tar.gz
  sha256: 60a080990d3c32d0d74a982dd397238a2d9bfcade884c6f1cf551bc9135d8685

build:
  entry_points:
    - featuretools = featuretools.__main__:cli
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6.*
  run:
    - click >=7.0.0
    - cloudpickle >=0.4.0
    - dask >=2.12.0
    - distributed >=2.12.0
    - numpy >=1.13.3
    - pandas >=0.24.1,<2.0.0
    - psutil >=5.4.8
    - python >=3.6.*
    - pyyaml >=3.12
    - scipy >=0.13.3
    - tqdm >=4.32.0

test:
  commands:
    - featuretools --help
    - featuretools info
    - featuretools list-primitives
    - pytest --pyargs featuretools
  imports:
    - featuretools
  requires:
    - boto3 >=1.10.45
    - composeml >=0.2.0
    - fastparquet >=0.1.6
    - moto >=1.3.13
    - pip >=0.20.2
    - pympler >=0.8
    - pytest >=5.2.*
    - python-graphviz >=0.8.4
    - smart_open >=1.8.4
  source_files:
    - featuretools/*

about:
  doc_url: https://docs.featuretools.com
  dev_url: https://github.com/Featuretools/featuretools/
  home: https://featuretools.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a framework for automated feature engineering

extra:
  recipe-maintainers:
    - kmax12
    - rwedge
