{% set version = "1.31.0" %}

package:
  name: featuretools
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/featuretools/featuretools-{{ version }}.tar.gz
  sha256: 01bfb17fcc1715b4c3623c7bc94a8982122c4a0fa03350ed478601bb81f90155

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.9.*
  run:
    - cloudpickle >=1.5.0
    - holidays >=0.17
    - numpy >=1.25.0
    - packaging >=20.0
    - pandas >=2.0.0
    - psutil >=5.7.0
    - python >=3.9.*
    - scipy >=1.10.0
    - tqdm >=4.66.3
    - woodwork >=0.28.0
test:
  commands:
    - pytest -n 2 --pyargs featuretools
  imports:
    - featuretools
  requires:
    - boto3 >=1.34.32
    - composeml >=0.8.0
    - graphviz !=2.47.2
    - moto >=5.0.0
    - pip >=21.3.1
    - pyarrow >=14.0.1
    - pympler >=0.8
    - pytest >=7.1.2
    - pytest-cov >=3.0.0
    - pytest-timeout >=2.1.0
    - pytest-xdist >=2.5.0
    - python-graphviz >=0.8.4
    - smart_open >=5.0.0
    - urllib3 >=1.26.18
    - dask >= 2023.2.0
    - distributed >= 2023.2.0
  source_files:
    - featuretools/*
    - pyproject.toml
    - LICENSE
    - README.md

about:
  doc_url: https://featuretools.alteryx.com
  dev_url: https://github.com/alteryx/Featuretools
  home: https://www.featuretools.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a framework for automated feature engineering
  description: |
    Featuretools is a framework to perform automated feature engineering. 
    It excels at transforming temporal and relational datasets into 
    feature matrices for machine learning.

extra:
  recipe-maintainers:
    - stefaniesmith
    - sbadithe
    - machineAYX
    - thehomebrewnerd
    - jeff-hernandez
    - dvreed77
