{% set version = "1.0.0rc1.dev0" %}

package:
  name: featuretools
  version: {{ version }}

source:
  url: https://test-files.pythonhosted.org/packages/b0/bc/f9749dbc6d523c9cd7ccfc42b55d9b5abec257a53dad43039d061c176ebd/featuretools-0.7.0.tar.gz
  sha256: ffdc476198ce0ca89d9282820c93b22c994e34865520dc588ba4afdada813731

build:
  entry_points:
    - featuretools = featuretools.__main__:cli
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7.*
  run:
    - click >=7.0.0
    - cloudpickle >=1.5.0
    - dask >=2021.2.0
    - distributed >=2021.2.0
    - numpy >=1.17.5
    - pandas >=1.3.0,<2.0.0
    - psutil >=5.6.6
    - python >=3.7.*
    - pyyaml >=5.4
    - scipy >=1.3.2
    - tqdm >=4.32.0
    - woodwork >=0.8.1

test:
  commands:
    - featuretools --help
    - featuretools info
    - featuretools list-primitives
    - pytest --pyargs featuretools
  imports:
    - featuretools
  requires:
    - boto3 >=1.17.46
    - composeml >=0.3.0
    - fastparquet==0.5.0
    - graphviz !=2.47.2
    - moto >=1.3.15
    - pip >=21.1.2
    - pympler >=0.8
    - pytest >=5.2.*
    - python-graphviz >=0.8.4
    - smart_open >=5.0.*
    - urllib3 >=1.26.5
    - pyarrow >=3.0.0
  source_files:
    - featuretools/*

about:
  doc_url: https://featuretools.alteryx.com
  dev_url: https://github.com/alteryx/Featuretools
  home: https://www.featuretools.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a framework for automated feature engineering
  description: |
    Featuretools is a framework to perform automated feature engineering. 
    It excels at transforming temporal and relational datasets into 
    feature matrices for machine learning.
    
    NOTICE:
    The upcoming release of Featuretools 1.0.0 contains several breaking changes. 
    For details on migrating to the new version, refer to Transitioning to Featuretools Version 1.0:
    
    
    https://featuretools.alteryx.com/en/woodwork-integration/resources/transition_to_ft_v1.0.html
    
    
    Please report any issues in the Featuretools GitHub repo or by messaging in Alteryx Open Source Slack.
extra:
  recipe-maintainers:
    - tuethan1999
    - rwedge
    - tamargrey
    - davesque
    - thehomebrewnerd
    - jeff-hernandez
    - gsheni
