{% set version = "0.5.0" %}

package:
  name: featuretools
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/featuretools/featuretools-{{ version }}.tar.gz
  sha256: fb15fea5eed0a180028bb8e1777f08ce3c8a9ce0f360c8bc185a923cb55a517b

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - pytest-runner >=4.2
    - python
  run:
    - boto3 >=1.9.51
    - botocore >=1.12.51
    - click >=7.0.0
    - cloudpickle >=0.4.0
    - dask >=0.19.4
    - distributed >=1.24.2
    - future >=0.16.0
    - numpy >=1.13
    - pandas >=0.23.*
    - psutil >=5.4.8
    - python
    - pyyaml >=3.12
    - scikit-learn >=0.20.0
    - smart_open >=1.7.1
    - s3fs >=0.1.2
    - toolz >=0.8.2
    - tqdm >=4.19.2

test:
  commands:
    - featuretools info --help
    - featuretools install --help
    - featuretools list-primitives
    - pytest featuretools/tests
  imports:
    - featuretools
  requires:
    - certifi >=2018.11.29
    - fastparquet >=0.1.6,<0.2
    - mock 2.0.*
    - pympler >=0.5,<0.6
    - pytest >=3.8.2,<3.9
    - pytest-xdist >=1.23.2,<1.24
  source_files:
    - featuretools/tests/*

about:
  doc_url: https//:docs.featuretools.com
  dev_url: https://github.com/Featuretools/featuretools/
  home: https://featuretools.com
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'a framework for automated feature engineering'

extra:
  recipe-maintainers:
    - kmax12
    - rwedge
