{% set version = "0.13.4.dev0" %}

package:
  name: featuretools
  version: {{ version }}

source:
  url: https://test-files.pythonhosted.org/packages/22/54/f5cb359950352db3000dfcdac3825a703cd5cb98c4eed80b10080c35899a/featuretools-0.13.4.dev0.tar.gz
  sha256: daeeae3f65cbed749f8d3509c5412f80cf6a365cb25c8a14556641cec26bdb05

build:
  entry_points:
    - featuretools = featuretools.__main__:cli
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.5.*
  run:
    - click >=7.0.0
    - cloudpickle >=0.4.0
    - dask >=1.1.0
    - distributed >=1.24.2
    - numpy >=1.13.3
    - pandas >=0.24.1
    - psutil >=5.4.8
    - python >=3.5.*
    - pyyaml >=3.12
    - scipy >=0.13.3
    - tqdm >=4.32.0

test:
  commands:
    - featuretools --help
    - featuretools info
    - featuretools list-primitives
    - pytest --doctest-modules featuretools/
  imports:
    - featuretools
  requires:
    - boto3 >=1.10.45
    - fastparquet >=0.1.6
    - moto >=1.3.13
    - pympler >=0.5,<0.6
    - pytest >=5.2.*
    - python-graphviz >=0.8.4
    - smart_open >=1.8.4
  source_files:
    - featuretools/*

about:
  doc_url: https://docs.featuretools.com
  dev_url: https://github.com/Featuretools/featuretools/
  home: https://featuretools.com
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a framework for automated feature engineering

extra:
  recipe-maintainers:
    - kmax12
    - rwedge
