{% set version = "0.24.1.dev0" %}

package:
  name: featuretools
  version: {{ version }}

source:
  url: https://test-files.pythonhosted.org/packages/4b/4f/20a94a768e80c2bde63febf166f3c45949b02206a0de6ebfb75095796845/featuretools-0.24.1.dev0.tar.gz
  sha256: fa0b444055f8bb4046d79823f4b0226b740cbc1ad1016b2ca80c35138168ec29

build:
  entry_points:
    - featuretools = featuretools.__main__:cli
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7.*
  run:
    - click >=7.0.0
    - cloudpickle >=0.4.0
    - dask >=2.12.0
    - distributed >=2.12.0
    - numpy >=1.16.6
    - pandas >=1.2.0,<2.0.0
    - psutil >=5.6.6
    - python >=3.7.*
    - pyyaml >=5.4
    - scipy >=1.3.2
    - tqdm >=4.32.0

test:
  commands:
    - featuretools --help
    - featuretools info
    - featuretools list-primitives
    - pytest --pyargs featuretools
  imports:
    - featuretools
  requires:
    - boto3 >=1.17.46
    - composeml >=0.3.0
    - fastparquet==0.5.0
    - moto >=1.3.15
    - pip >=19.0.2
    - pympler >=0.8
    - pytest >=5.2.*
    - python-graphviz >=0.8.4
    - smart_open >=5.0.*
    - urllib3 >=1.26.4
  source_files:
    - featuretools/*

about:
  doc_url: https://docs.featuretools.com
  dev_url: https://github.com/Featuretools/featuretools/
  home: https://featuretools.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a framework for automated feature engineering

extra:
  recipe-maintainers:
    - gsheni
    - rwedge
