{% set version = "1.23.0" %}

package:
  name: featuretools
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/featuretools/featuretools-{{ version }}.tar.gz
  sha256: c6acc78eac466f49c2e79908078c45b1baba286943ee3227a11c05622c18411a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.8.*, <3.11.0
  run:
    - cloudpickle >=1.5.0
    - dask !=2022.10.1, >=2022.2.0
    - distributed !=2022.10.1, >=2022.2.0
    - holidays >=0.13
    - numpy >=1.21.0
    - packaging >=20.0
    - pandas >=1.4.0
    - psutil >=5.6.6
    - python >=3.8.*, <3.11.0
    - scipy >=1.4.0
    - tqdm >=4.32.0
    - woodwork >=0.18.0
test:
  commands:
    - pytest -n 2 --pyargs featuretools
  imports:
    - featuretools
  requires:
    - boto3 >=1.17.46
    - composeml >=0.8.0
    - graphviz !=2.47.2
    - moto >=3.0.7
    - pip >=21.3.1
    - pyarrow >=3.0.0
    - pympler >=0.8
    - pytest >=7.1.2
    - pytest-cov >=3.0.0
    - pytest-timeout >=2.1.0
    - pytest-xdist >=2.5.0
    - python-graphviz >=0.8.4
    - smart_open >=5.0.0
    - urllib3 >=1.26.5
  source_files:
    - featuretools/*
    - pyproject.toml
    - LICENSE
    - README.md

about:
  doc_url: https://featuretools.alteryx.com
  dev_url: https://github.com/alteryx/Featuretools
  home: https://www.featuretools.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a framework for automated feature engineering
  description: |
    Featuretools is a framework to perform automated feature engineering. 
    It excels at transforming temporal and relational datasets into 
    feature matrices for machine learning.

extra:
  recipe-maintainers:
    - stefaniesmith
    - sbadithe
    - ozzieD
    - machineAYX
    - rwedge
    - tamargrey
    - thehomebrewnerd
    - jeff-hernandez
    - gsheni
    - dvreed77
