{% set version = "0.8.0rc3" %}

package:
  name: featuretools
  version: {{ version }}

source:
  url: https://test-files.pythonhosted.org/packages/4f/da/76c417cb82528701a848ecd3504f68d328e1af5138ed8d814b87d5c6956e/featuretools-0.8.0rc3.tar.gz
  sha256: 27c3a869903064c04e1ea1bc2fdedfe1477e10649c537e43deb794b69d8d101b

build:
  entry_points:
    - featuretools = featuretools.__main__:cli
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - pytest-runner ==4.2
    - python
  run:
    - click >=7.0.0
    - cloudpickle >=0.4.0
    - dask >=1.1.0
    - distributed >=1.24.2
    - funcsigs >=1.0.2  # [py2k]
    - future >=0.16.0
    - numpy >=1.13.3
    - pandas >=0.23.*
    - psutil >=5.4.8
    - python
    - pyyaml >=3.12
    - scikit-learn >=0.20.*,<0.21  # [py2k]
    - scikit-learn >=0.20.*  # [py3k]
    - toolz >=0.8.2
    - tqdm >=4.19.2

test:
  commands:
    - featuretools --help
    - featuretools info --help
    - featuretools list-primitives
    - pytest --doctest-modules featuretools/
  imports:
    - featuretools
  requires:
    - fastparquet >=0.1.6
    - mock 2.0.*
    - pympler >=0.5,<0.6
    - pytest >=4.1.*,<4.2
    - pytest-xdist >=1.26.1
    - python-graphviz >=0.8.4  # [not win]
    - python-graphviz =0.8.4=py27_1002  # [win and py2k]
    - python-graphviz =0.8.4=py36_1002  # [win and py==36]
    - python-graphviz =0.8.4=py37_1002  # [win and py==37]
  source_files:
    - featuretools/*

about:
  doc_url: https://docs.featuretools.com
  dev_url: https://github.com/Featuretools/featuretools/
  home: https://featuretools.com
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'a framework for automated feature engineering'

extra:
  recipe-maintainers:
    - kmax12
    - rwedge
