{% set version = "1.3.0.dev0" %}

package:
  name: featuretools
  version: {{ version }}

source:
  url: https://test-files.pythonhosted.org/packages/eb/1e/07158bfa5b13581eb96c4ac8d9e9dc5456450254c5996b691bd2d28cda1f/featuretools-1.3.0.dev0.tar.gz
  sha256: b813ab289aead5a2d912b8a22453ec0f8544ed68d3afa0d4e9c6ede4e34986e4

build:
  entry_points:
    - featuretools = featuretools.__main__:cli
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7.*
  run:
    - click >=7.0.0
    - cloudpickle >=1.5.0
    - dask >=2021.10.0
    - distributed >=2021.10.0
    - numpy >=1.18.0
    - pandas >=1.3.0,<2.0.0
    - psutil >=5.6.6
    - python >=3.7.*
    - pyyaml >=5.4
    - scipy >=1.3.2
    - tqdm >=4.32.0
    - woodwork >=0.8.1

test:
  commands:
    - featuretools --help
    - featuretools info
    - featuretools list-primitives
    - pytest -n 2 --pyargs featuretools
  imports:
    - featuretools
  requires:
    - boto3 >=1.17.46
    - composeml >=0.3.0
    - fastparquet==0.5.0
    - graphviz !=2.47.2
    - moto >=1.3.15
    - pip >=21.3.1
    - pympler >=0.8
    - pytest >=5.2.*
    - python-graphviz >=0.8.4
    - smart_open >=5.0.*
    - urllib3 >=1.26.5
    - pyarrow >=3.0.0
    - pytest-xdist >=1.26.1
  source_files:
    - featuretools/*

about:
  doc_url: https://featuretools.alteryx.com
  dev_url: https://github.com/alteryx/Featuretools
  home: https://www.featuretools.com
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: a framework for automated feature engineering
  description: |
    Featuretools is a framework to perform automated feature engineering. 
    It excels at transforming temporal and relational datasets into 
    feature matrices for machine learning.

extra:
  recipe-maintainers:
    - tuethan1999
    - rwedge
    - tamargrey
    - davesque
    - thehomebrewnerd
    - jeff-hernandez
    - gsheni
