{% set version = "0.6.1" %}

package:
  name: featuretools
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/f/featuretools/featuretools-{{ version }}.tar.gz
  sha256: 3fde0e77dda08e1aa5d79449bfe301fd61d3850d0e82d49b72279d3b5e2e8f9d

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - pytest-runner ==4.2
    - python
  run:
    - botocore >=1.12.51
    - boto3 >=1.9.51
    - click >=7.0.0
    - cloudpickle >=0.4.0
    - dask >=1.1.0
    - distributed >=1.24.2
    - future >=0.16.0
    - numpy >=1.13.3
    - pandas >=0.23.*
    - psutil >=5.4.8
    - python
    - pyyaml >=3.12
    - scikit-learn >=0.20.0
    - smart_open >=1.7.1
    - toolz >=0.8.2
    - tqdm >=4.19.2

test:
  commands:
    - featuretools --help
    - featuretools info --help
    - featuretools install --help
    - featuretools list-primitives
    - pytest featuretools/tests
  imports:
    - featuretools
  requires:
    - fastparquet >=0.1.6,<0.2
    - mock 2.0.*
    - pympler >=0.5,<0.6
    - pytest >=4.1.*,<4.2
    - pytest-xdist >=1.26.1
    - python-graphviz >=0.8.4
    - s3fs >=0.1.5
  source_files:
    - featuretools/tests/*

about:
  doc_url: https://docs.featuretools.com
  dev_url: https://github.com/Featuretools/featuretools/
  home: https://featuretools.com
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'a framework for automated feature engineering'

extra:
  recipe-maintainers:
    - kmax12
    - rwedge
